"""empty message

Revision ID: 2af6705ccd35
Revises: 6ecf43cff158
Create Date: 2025-11-11 21:08:17.399162

"""

from typing import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2af6705ccd35"
down_revision: Union[str, None] = "6ecf43cff158"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uix_column_name", "table_report_row", ["id", "unique_value"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uix_column_name", "table_report_row", type_="unique")
    # ### end Alembic commands ###
