"""empty message

Revision ID: ab02bf8d09b2
Revises:
Create Date: 2025-11-17 14:20:11.076595

"""

from typing import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ab02bf8d09b2"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("template", sa.Column("id", sa.Integer(), nullable=False), sa.PrimaryKeyConstraint("id"))
    op.create_index(op.f("ix_template_id"), "template", ["id"], unique=False)
    op.create_table("user", sa.Column("id", sa.Integer(), nullable=False), sa.PrimaryKeyConstraint("id"))
    op.create_index(op.f("ix_user_id"), "user", ["id"], unique=False)
    op.create_table(
        "table_report",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("template_id", sa.Integer(), nullable=False),
        sa.Column("columns_metadata", sa.JSON(), nullable=True),
        sa.Column("total_rows", sa.Integer(), nullable=False),
        sa.Column("additional_params", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["template_id"], ["template.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_table_report_id"), "table_report", ["id"], unique=False)
    op.create_table(
        "table_report_row",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("unique_value", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("report_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["report_id"], ["table_report.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_table_report_row_id"), "table_report_row", ["id"], unique=False)
    op.create_index(op.f("ix_table_report_row_is_deleted"), "table_report_row", ["is_deleted"], unique=False)
    op.create_index(op.f("ix_table_report_row_report_id"), "table_report_row", ["report_id"], unique=False)
    op.create_index(op.f("ix_table_report_row_unique_value"), "table_report_row", ["unique_value"], unique=False)
    op.create_table(
        "table_report_value",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("column_name", sa.String(length=255), nullable=False),
        sa.Column("value", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("row_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["row_id"], ["table_report_row.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_table_report_value_column_name"), "table_report_value", ["column_name"], unique=False)
    op.create_index(op.f("ix_table_report_value_id"), "table_report_value", ["id"], unique=False)
    op.create_index(op.f("ix_table_report_value_row_id"), "table_report_value", ["row_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_table_report_value_row_id"), table_name="table_report_value")
    op.drop_index(op.f("ix_table_report_value_id"), table_name="table_report_value")
    op.drop_index(op.f("ix_table_report_value_column_name"), table_name="table_report_value")
    op.drop_table("table_report_value")
    op.drop_index(op.f("ix_table_report_row_unique_value"), table_name="table_report_row")
    op.drop_index(op.f("ix_table_report_row_report_id"), table_name="table_report_row")
    op.drop_index(op.f("ix_table_report_row_is_deleted"), table_name="table_report_row")
    op.drop_index(op.f("ix_table_report_row_id"), table_name="table_report_row")
    op.drop_table("table_report_row")
    op.drop_index(op.f("ix_table_report_id"), table_name="table_report")
    op.drop_table("table_report")
    op.drop_index(op.f("ix_user_id"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_template_id"), table_name="template")
    op.drop_table("template")
    # ### end Alembic commands ###
