"""empty message

Revision ID: 41f8d2abd256
Revises: 2af6705ccd35
Create Date: 2025-11-14 13:23:41.150564

"""

from typing import Sequence
from typing import Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "41f8d2abd256"
down_revision: Union[str, None] = "2af6705ccd35"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uix_column_name"), "table_report_row", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uix_column_name"), "table_report_row", ["id", "unique_value"], postgresql_nulls_not_distinct=False
    )
    # ### end Alembic commands ###
